---
- name: Install nginx with vhosts
  hosts: webservers
  become: yes
  become_method: sudo
  remote_user: runner
  gather_facts: no

  vars:
    sites:
    - "fizfak.com"
    - "mehmat.com"
    - "biofak.com"

  roles:
  - nginx_vhosts
