---
- name: Install nginx
  ansible.builtin.apt:
    name: nginx
    state: present

- name: Config for vhosts
  ansible.builtin.template:
    src: 'site.conf.j2'
    dest: '/etc/nginx/conf.d/site-{{ item }}.conf'
    mode: '0600'
  loop: '{{ sites }}'
  notify: Restart nginx

- name: Create folders for sites
  ansible.builtin.file:
    path: '/var/www/{{ item }}/'
    state: 'directory'
    mode: '0600'
  loop: '{{ sites }}'

- name: Copy indices from templates
  ansible.builtin.template:
    src: './index.html.j2'
    dest: '/var/www/{{ item }}/index.html'
    owner: root
    group: root
    mode: '0644'
  loop: '{{ sites }}'
